language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
#    - "3.7-dev"
#    - "3.6.0b2"
#   - "nightly"
#

before_install:
    - sudo apt-get -qq update
      #    - sudo apt-get install libhdf5
    - sudo apt-get install libhdf5-serial-dev
    - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
    - uname -a
    - free -m
    - df -h
    - pip install -U virtualenv
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python -V
    - echo $TRAVIS_PYTHON_VERSION
    - pip install -U pip setuptools
    - pip install -U numpy cython
    - pip install -U pytest mock
    - pip install -U statsmodels==0.8.0rc1
    - pip install -U tables
    - pip install -U numexpr
    - pip install -U h5py
    - pip install -U tornado
    - pip install -U requests
    - pip install matplotlib==2.0.0
    - ls -al

install:
    - pip install .

script: py.test venv/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/km3pipe
